version: "3.7"

networks:
  frontend_network:
  backend_network:

services:
  frontend:
    build: ./frontend/
    image: frontend-historia-clinica:1.0
    expose:
      - 3000
    ports:
      - 3000:3000
    volumes:
      - ./frontend:/app
      - /app/node_modules/
    networks:
      - frontend_network
    command: "npm run dev"

  backend:
    image: backend-historia-clinica:1.0
    build: ./backend/
    working_dir: /home/app
    expose:
      - "8000"
    ports:
      - 8000:8000
    volumes:
      - ./backend:/home/app
    networks:
      - backend_network
    command: "python3 manage.py runserver 0.0.0.0:8000"
