# Generated by Django 4.2.7 on 2023-11-21 20:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FactorRiesgo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True, verbose_name='Nombre')),
                ('sintomas', models.TextField(default='', verbose_name='Sintomas')),
                ('descripcion', models.TextField(verbose_name='Descripción')),
            ],
        ),
        migrations.CreateModel(
            name='FactorRiesgoPaciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_paciente', models.IntegerField(verbose_name='ID Paciente')),
                ('estado', models.CharField(choices=[('detected', 'Detectado'), ('open', 'Abierto'), ('edited', 'Editado'), ('closed', 'Cerrado')], default='detected', max_length=10, verbose_name='Estado')),
                ('notas', models.TextField(blank=True, default='', verbose_name='Notas')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('ultima_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Ultima actualización')),
                ('factor_riesgo', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='factores_de_riesgo.factorriesgo')),
            ],
        ),
        migrations.CreateModel(
            name='HistorialCambiosFactoresRiesgo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('detected', 'Detectado'), ('open', 'Abierto'), ('edited', 'Editado'), ('closed', 'Cerrado')], max_length=10, verbose_name='Estado')),
                ('notas', models.TextField(blank=True, default='', verbose_name='Notas')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('id_factor_riesgo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='factores_de_riesgo.factorriesgopaciente')),
            ],
        ),
    ]
