# Generated by Django 4.2.7 on 2023-11-22 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factores_de_riesgo', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='factorriesgo',
            name='sintomas',
        ),
        migrations.AddField(
            model_name='factorriesgo',
            name='razones',
            field=models.TextField(default='', verbose_name='Razones'),
        ),
    ]
