# Generated by Django 4.2.7 on 2023-11-20 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProblemaClinico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True, verbose_name='Nombre')),
                ('descripcion', models.TextField(verbose_name='Descripción')),
            ],
        ),
        migrations.CreateModel(
            name='ProblemaClinicoPaciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_paciente', models.IntegerField(unique=True, verbose_name='ID Paciente')),
                ('estado', models.CharField(choices=[('detected', 'Detectado'), ('open', 'Abierto'), ('edited', 'Editado'), ('closed', 'Cerrado')], max_length=10, verbose_name='Estado')),
                ('fecha_creacion', models.DateField(auto_now=True, verbose_name='Fecha de creación')),
                ('problema_clinico', models.ManyToManyField(to='problemas_clinicos.problemaclinico')),
            ],
        ),
    ]
