# Generated by Django 4.2.7 on 2023-11-20 22:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('problemas_clinicos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='problemaclinico',
            name='sintomas',
            field=models.TextField(default='', verbose_name='Sintomas'),
        ),
        migrations.RemoveField(
            model_name='problemaclinicopaciente',
            name='problema_clinico',
        ),
        migrations.AddField(
            model_name='problemaclinicopaciente',
            name='problema_clinico',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.DO_NOTHING, to='problemas_clinicos.problemaclinico'),
            preserve_default=False,
        ),
    ]
