# Generated by Django 4.2.7 on 2023-11-20 23:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('problemas_clinicos', '0002_problemaclinico_sintomas_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistorialCambios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('detected', 'Detectado'), ('open', 'Abierto'), ('edited', 'Editado'), ('closed', 'Cerrado')], max_length=10, verbose_name='Estado')),
                ('fecha', models.DateField(auto_now=True, verbose_name='Fecha')),
                ('id_problema_paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='problemas_clinicos.problemaclinicopaciente')),
            ],
        ),
    ]
