# Generated by Django 4.2.7 on 2023-11-20 23:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('problemas_clinicos', '0003_historialcambios'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='HistorialCambios',
            new_name='HistorialCambiosProblemas',
        ),
    ]
