# Generated by Django 4.2.7 on 2023-11-20 23:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('problemas_clinicos', '0004_rename_historialcambios_historialcambiosproblemas'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='HistorialCambiosProblemas',
            new_name='HistorialCambiosProblema',
        ),
    ]
