# Generated by Django 4.2.7 on 2023-11-20 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problemas_clinicos', '0005_rename_historialcambiosproblemas_historialcambiosproblema'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problemaclinicopaciente',
            name='estado',
            field=models.CharField(choices=[('detected', 'Detectado'), ('open', 'Abierto'), ('edited', 'Editado'), ('closed', 'Cerrado')], default='detected', max_length=10, verbose_name='Estado'),
        ),
    ]
