# Generated by Django 4.2.7 on 2023-11-21 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problemas_clinicos', '0006_alter_problemaclinicopaciente_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='problemaclinicopaciente',
            name='ultima_actualizacion',
            field=models.DateTimeField(auto_now=True, verbose_name='Ultima actualización'),
        ),
        migrations.AlterField(
            model_name='historialcambiosproblema',
            name='fecha',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='problemaclinicopaciente',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación'),
        ),
    ]
