# Generated by Django 4.2.7 on 2023-11-21 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problemas_clinicos', '0007_problemaclinicopaciente_ultima_actualizacion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problemaclinicopaciente',
            name='id_paciente',
            field=models.IntegerField(verbose_name='ID Paciente'),
        ),
    ]
