# Generated by Django 4.2.7 on 2023-11-21 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problemas_clinicos', '0008_alter_problemaclinicopaciente_id_paciente'),
    ]

    operations = [
        migrations.AddField(
            model_name='historialcambiosproblema',
            name='notas',
            field=models.TextField(default='', verbose_name='Notas'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='problemaclinicopaciente',
            name='notas',
            field=models.TextField(default='', verbose_name='Notas'),
        ),
    ]
