# Generated by Django 4.2.7 on 2023-11-21 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problemas_clinicos', '0009_historialcambiosproblema_notas_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historialcambiosproblema',
            name='notas',
            field=models.TextField(default='', verbose_name='Notas'),
        ),
    ]
