# Generated by Django 4.2.7 on 2023-11-21 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problemas_clinicos', '0010_alter_historialcambiosproblema_notas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historialcambiosproblema',
            name='notas',
            field=models.TextField(blank=True, default='', verbose_name='Notas'),
        ),
        migrations.AlterField(
            model_name='problemaclinicopaciente',
            name='notas',
            field=models.TextField(blank=True, default='', verbose_name='Notas'),
        ),
    ]
